apiVersion: v1
kind: Service
metadata:
  name: green-greeting-app
spec:
  type: NodePort
  selector:
    app: green-greeting-app
    version: green
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30091