apiVersion: v1
kind: Service
metadata:
  name: greeting-app
  labels:
    app: greeting-app
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: greeting-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      name: greeting-app
      labels:
        app: greeting-app
    spec:
      containers:
        - name: greeting-app
          image: greeting-app:1.0
          imagePullPolicy: Never
          env:
          - name: BW_LOGLEVEL
            value: "ERROR"
          - name: BW_PROFILE
            value: "default"
          ports:
            - containerPort: 8081
            - name: readiness-port
              containerPort: 7777
          readinessProbe:
            httpGet:
              path: /_ping
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 15
