apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: greeting-app
      version: 1.1
  template:
    metadata:
      name: greeting-app
      labels:
        app: greeting-app
        version: 1.1
    spec:
      containers:
        - name: greeting-app
          image: greeting-app:1.1
          imagePullPolicy: Never
          env:
          - name: BW_LOGLEVEL
            value: "ERROR"
          - name: BW_PROFILE
            value: "default"
          ports:
            - containerPort: 8081
            - name: readiness-port
              containerPort: 7777
          readinessProbe:
            httpGet:
              path: /_ping
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 15
