apiVersion: v1
kind: Service
metadata:
  name: greeting-app
  labels:
    app: greeting-app
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30092
  selector:
    app: green-greeting-app
    version: green